const States = [
  {
    id: "Abia",
    capital: "Umuahia",
    slogan: "God's Own State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Adamawa",
    capital: "Yola",
    slogan: "Land of Beauty",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Akwa Ibom",
    capital: "Uyo",
    slogan: "Land of Promise",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Anambra",
    capital: "Awka",
    slogan: "Light of the Nation",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Bauchi",
    capital: "Bauchi",
    slogan: "Pearl of Tourism",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Bayelsa",
    capital: "Yenagoa",
    slogan: "Glory of all lands",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Benue",
    capital: "Makurdi",
    slogan: "Food Basket of the Nation",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Borno",
    capital: "Maiduguri",
    slogan: "Home of Peace",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Cross River",
    capital: "Calabar",
    slogan: "The People's Paradise",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Delta",
    capital: "Asaba",
    slogan: "The Big Heart ",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Ebonyi",
    capital: "Abakaliki",
    slogan: "Sat of the Nation",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Edo",
    capital: "Benin City",
    slogan: "Heart Beat of Nigeria",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Ekiti",
    capital: "Ado-Ekiti",
    slogan: "Land of Honour and Integrity",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Enugu",
    capital: "Enugu",
    slogan: "Coal City State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Gombe",
    capital: "Gombe",
    slogan: "Jewel in the Savannah",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Imo",
    capital: "Owerri",
    slogan: "Eastern Heartland",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Jigawa",
    capital: "Duste",
    slogan: "The New World",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Kaduna",
    capital: "Kaduna",
    slogan: "Centre of Learning",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Kano",
    capital: "Kano",
    slogan: "Centre of Commerce",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Katsina",
    capital: "Katsina",
    slogan: "Home of Hospitaity",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Kebbi",
    capital: "Birnin Kebbi",
    slogan: "Land of Equity",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Kogi",
    capital: "Lokoja",
    slogan: "The Confluence State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Kwara",
    capital: "Ilorin",
    slogan: "State of Harmony",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Lagos",
    capital: "Ikeja",
    slogan: "Centre of Excellence",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Nasarawa",
    capital: "Lafia",
    slogan: "Home of Solid Minerals",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Niger",
    capital: "Minna",
    slogan: "The Power State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Ogun",
    capital: "Abeokuta",
    slogan: "Gateway State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Ondo",
    capital: "Akure",
    slogan: "Sunshine State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Osun",
    capital: "Oshogbo",
    slogan: "Land of Virtue",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Oyo",
    capital: "Ibadan",
    slogan: "Pace Setter State",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Plateau",
    capital: "Jos",
    slogan: "Home of Peace and Tourism",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Rivers",
    capital: "Port Harcourt",
    slogan: "Treasure Base of the Nation",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Sokoto",
    capital: "Sokoto",
    slogan: "Seat of the Caliphate",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Taraba",
    capital: "Jalingo",
    slogan: "Nature's Gift to the Nation",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Yobe",
    capital: "Damaturu",
    slogan: "Pride of the Sahel",
    lga: [],
    currentGovernor: "",
  },
  {
    id: "Zamfara",
    capital: "Gusau",
    slogan: "Farming is Our Pride",
    lga: [],
    currentGovernor: "",
  },
];

const findState = (state) => {
  let stateTemp = [];
  stateTemp = States.filter((value) => {
    return value.id.toUpperCase().includes(state.toUpperCase());
  });
  return stateTemp;
};

module.exports = { stateList: States, findState: findState };
